ishida-0622/u22-2023

backend/app/src/main/kotlin/tic/u22/Utils.kt

feat: Utilsの追加

---

backend/app/src/main/kotlin/tic/u22/Utils.kt

fix: update user-data-class

---

backend/app/src/main/kotlin/tic/u22/App.kt
backend/app/src/main/kotlin/tic/u22/Utils.kt

converts to map in both test and prod

feat: formatter

---

frontend/src/components/elements/Menubar/index.module.scss
frontend/src/components/elements/Menubar/index.tsx

style: メニューバーのCSS

---

frontend/src/components/elements/Menubar/index.module.scss
frontend/src/components/elements/Menubar/index.tsx

メニューバー
一般ユーザーの画面の下部に表示されるボタンの集まり

feat: menubar

---

backend/app/src/main/kotlin/tic/u22/App.kt
backend/app/src/main/kotlin/tic/u22/Others.kt
backend/app/src/main/kotlin/tic/u22/S3.kt
backend/app/src/main/kotlin/tic/u22/Utils.kt
frontend/src/components/elements/AdminMenubar/index.module.scss
frontend/src/components/pages/SendEmail/index.tsx
frontend/src/components/pages/login/index.tsx
frontend/src/components/pages/signup/index.tsx
frontend/src/features/auth/types/index.ts
frontend/src/features/auth/types/signup/index.ts
frontend/src/features/puzzle/types/pause/index.ts
frontend/src/features/puzzle/types/restart/index.ts
frontend/src/store/user/index.ts

アドミンメニューバーのデザイン。
pxをremと%に修正したぐらいです。

style: アドミンメニューバーのデザイン

---

frontend/src/components/pages/PuzzlePlay/index.module.scss
frontend/src/components/pages/PuzzlePlay/index.tsx
frontend/src/features/puzzle/play/Board/index.module.scss
frontend/src/features/puzzle/play/Board/index.tsx
frontend/src/features/puzzle/play/Piece/index.tsx
package-lock.json

style: パズル画面のCSS

---

frontend/src/components/pages/PostAnnouncementList/index.module.scss
frontend/src/components/pages/PostAnnouncementList/index.tsx

style: お知らせ一覧画面のデザイン作成

---

frontend/src/components/pages/PuzzleList/index.module.scss
frontend/src/components/pages/PuzzleList/index.tsx

style: 問題管理画面のデザイン

---

frontend/src/components/pages/AccountInfo/index.module.scss
frontend/src/components/pages/AccountInfo/index.tsx

Style-account-info

---

frontend/src/components/elements/AdminMenubar/index.module.scss

style: デザインの編集

---

frontend/src/components/elements/AdminMenubar/index.module.scss

style: デザインの変更

---

frontend/src/components/pages/PuzzleList/index.module.scss
frontend/src/components/pages/PuzzleList/index.tsx

文字サイズによって位置が変わってしまうと思われるので変わらないように修正しました。

style: ボタンの右寄せを文字サイズに対応

---

frontend/src/components/pages/PostAnnouncementList/index.module.scss
frontend/src/components/pages/PostAnnouncementList/index.tsx

ペンマークとゴミ箱マークボタンの右寄せをしました。
タイトルを～管理画面は管理で統一します。
ボタンのホバー時のカラーを修正しました。

style: ボタンの右寄せとその他微調整

---

frontend/src/components/pages/admin/PostAnnouncementList/index.module.scss
frontend/src/components/pages/admin/PostAnnouncementList/index.tsx

style: お知らせ管理画面モーダルウィンドウのデザイン

---

frontend/src/components/pages/admin/PostAnnouncementList/index.module.scss
frontend/src/components/pages/admin/PostAnnouncementList/index.tsx

style: お知らせ一覧

---

frontend/src/components/pages/PuzzleList/index.module.scss
frontend/src/components/pages/PuzzleList/index.tsx

モーダルウィンドウをデザインしました。
ペンマークとゴミ箱マークの配置の修正が反映されてなかったみたいなので再度修正しました。

style: パズル問題管理画面のモーダルウィンドウのデザイン

---

frontend/src/components/pages/admin/adminTop/index.module.scss
frontend/src/components/pages/admin/adminTop/index.tsx

adminTopページのデザインを修正しました。
一番しっくりくるのにしました。

style: adminTopページデザインの修正

---

frontend/src/components/pages/admin/BookList/index.tsx

モーダルウィンドウが画面外までのサイズになった時にスクロールが無効化されないように修正しました。

style: 本棚管理画面のモーダルウィンドウの修正

---

frontend/src/components/pages/admin/PostAnnouncementList/index.module.scss
frontend/src/components/pages/admin/PostAnnouncementList/index.tsx

style: お知らせ投稿画面モーダルウィンドウの修正
